spring:
  profiles:
    active: dev


  cloud:
    gcp:
      project-id: bustling-kayak-438602-m8
      spanner:
        instance-id: useractions-track
        database: useractiontracking
        credentials:
          location: file:C:\Users\Administrator\Desktop\bustling-kayak-438602-m8-27ee465cb15e.json